### PR TITLE
Support for running Rebus.GoogleCloudPubSub against local emulator

### PR DESCRIPTION
**Pull request by torangel**
- Made GoogleCloudPubSubTransport respect emulator env variabables if available
- Upgraded test project to dotnet6
- Instructions on various ways to run tests (emulator and cloud)
- Added docker-compose based test setup with no external requirements

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by torangel** [comment]
This to address

> In all languages except for Java and C#, if you have set PUBSUB_EMULATOR_HOST as described in [Setting environment variables](https://cloud.google.com/pubsub/docs/emulator#env), the Pub/Sub client libraries automatically call the API running in the local instance rather than Pub/Sub.
> 
> However, C# and Java client libraries require you to modify your code to use the emulator

https://cloud.google.com/pubsub/docs/emulator#accessing_environment_variables

**Comment by mookid8000** [comment]
Cool 🙂 let me know when the PR is ready for review

**Comment by torangel** [comment]
Should be ready now :)
Based on learnings from hosting Rebus in GCE I made two more modifications as shown in the last commits:

- GOOGLE_APPLICATION__CREDENTIALS is not always injected/available as I first believed, but rather some OIDC "magic" is going on under the hood managed by the Google SDK in our instance - Therefore removed the hard depency/check on the env. variable.
- Which in turn makes it difficult to "infer" the projectId from the credential - which might be a bad idea anyways.
(https://stackoverflow.com/questions/55960504/how-do-i-get-projectid-from-googlecredentials)

**Comment by mookid8000** [comment]
Coool! It's out as Rebus.GoogleCloudPubSub 0.0.6 on Nuget.org now 🙂 

Thanks for contributing ❤️

**Pull request merged**
