### PR TITLE
feat(message-converter): add support for customer message converter

### PR DESCRIPTION
**Pull request by goliveiracod**
This change introduces support for a custom message converter to handle conversions between Rebus and Google Pub/Sub, allowing greater flexibility in serializing and deserializing messages.

BREAKING CHANGE: this improvement changes the library's default conversion.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by goliveiracod** [comment]
hey @mookid8000 we got an error during the checks:

System.ArgumentException : Please ensure that tests are running with an environment variable named 'GOOGLE_APPLICATION_CREDENTIALS' that points to a JSON file containing appropriate Google credentials

is this step configured to run under the emulator?

**Comment by mookid8000** [comment]
@goliveiracod I don't think the tests have ever actually worked on Appveyor. Can you run them locally? And do they pass?

**Comment by goliveiracod** [comment]
> @goliveiracod I don't think the tests have ever actually worked on Appveyor. Can you run them locally? And do they pass?

They passed, everything is working fine.

**Comment by mookid8000** [comment]
Great 🙂 it's out as Rebus.GoogleCloudPubSub 0.0.9 on NuGet.org now.

Thanks for contributing! 👍

**Pull request merged**
